export default {
  GET_PLANETS: {
    FETCH: 'GET_PLANETS_FETCH',
    SUCCESS: 'GET_PLANETS_SUCCESS',
    ERROR: 'GET_PLANETS_ERROR',
  },
  GET_PLANET_BY_ID: {
    FETCH: 'GET_PLANET_BY_ID_FETCH',
    SUCCESS: 'GET_PLANET_BY_ID_SUCCESS',
    ERROR: 'GET_PLANET_BY_ID_ERROR',
  },
  GET_PEOPLE: {
    FETCH: 'GET_PEOPLE_FETCH',
    SUCCESS: 'GET_PEOPLE_SUCCESS',
    ERROR: 'GET_PEOPLE_ERROR',
  },
  CLEAR_PLANET_STATE: 'CLEAR_PLANET_STATE',
  CURRENT_PLANETS_PAGE: 'CURRENT_PLANETS_PAGE',
}